name: CI - Next.js

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Clone source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cài Node.js và bật cache npm tự động (nếu muốn)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 

      # Cache npm + Next.js build để tăng tốc
      - name: Cache npm and Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      # Cài dependencies
      - name: Install dependencies
        run: npm ci

      # Lint check
      - name: Run ESLint
        run: npm run lint

      # Build Next.js project
      - name: Build Next.js
        run: npm run build

      # Run tests (nếu có)
      - name: Run tests
        run: npm test
